[package]
name = "common"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_bytes.workspace = true
bytes.workspace = true
uuid.workspace = true
thiserror.workspace = true

[features]
default = []
