global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 3s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # HFT RTB Engine metrics
  - job_name: 'hft-engine'
    static_configs:
      - targets: ['hft-engine:9000']
    scrape_interval: 1s
    metrics_path: /metrics
    honor_labels: true

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  # Kafka JMX metrics (if enabled)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9308']
    scrape_interval: 10s
    metrics_path: /metrics

  # Redis metrics (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s
    metrics_path: /metrics